#pragma once
#include <memory>
#include "AUI/Common/AObject.h"
#include "AUI/Common/ATimer.h"
#include "AUI/Thread/AAsyncHolder.h"
#include "AUI/Thread/AEventLoop.h"
#include "Diary.h"
#include "IOpenAIChat.h"
#include "MetricsBreadcumbs.h"
#include "NotificationManager.h"
#include "OpenAITools.h"
#include "Worker.h"

class AppBase : public AObject {
public:
    struct Init {
        APath workingDir = "test_data";
        _<IOpenAIChat> openAI;
    };
    AppBase(Init init);
    virtual ~AppBase() = default;
    AString getSystemPrompt();

    AFuture<> diaryDumpMessages();
    AFuture<> diaryDumpMessages(IOpenAIChat::Session& temporaryContext);

    void actProactively();

    [[nodiscard]] Diary& diary() { return mDiary; }

    /**
     * @brief True when currently processing notification generated by actProactively.
     */
    [[nodiscard]] bool isActingProactively() const { return mActingProactively; }

    struct ToolCallEvent {
        AString toolName;
        AMap<AString, AString> breadcrumbLabels;
        AOptional<std::chrono::seconds> lastOpenedChatLastMessageTime;
    };
    emits<ToolCallEvent> toolCallFired;

    [[nodiscard]]
    const _<MetricsBreadcumbs>& metricBreadcumbs() const {
        return mMetricBreadcumbs;
    }

    virtual AString onCleanContext() const;

    NotificationManager& notificationManager() {
        return mNotificationManager;
    }

    /**
     * @brief Called by the main coroutine when a notification was processed.
     */
    virtual void onOffline() {}

    [[nodiscard]]
    const _<IOpenAIChat>& openAI() const noexcept {
        return mInit.openAI;
    }

    /**
     * @brief Called by the main coroutine during LLM inference streaming to observe which tool calls LLM is about to
     * perform.
     * @details
     * Can be used to send typing action as soon as send_telegram_message tool call appears in tools.
     */
    virtual void onResponseAssembling(IOpenAIChat::Response response) {}

    /**
     * @brief Adds always available actions
     */
    virtual void updateTools(OpenAITools& actions, const IOpenAIChat::Session& temporaryContext);


    void wakeUpIfSleeping();

protected:
    AAsyncHolder mAsync;

    // Set by llmuiOpenTelegramChat; read by updateTools to populate ToolCallEvent.
    AOptional<std::chrono::system_clock::time_point> mLastOpenedChatLastMessageTime;


private:
    _<MetricsBreadcumbs> mMetricBreadcumbs = _new<MetricsBreadcumbs>();
    const Init mInit;
    AFuture<> mNotificationsSignal;
    _<ATimer> mWakeupTimer;
    NotificationManager mNotificationManager;
    AString mSystemPromptSuffix;

    bool mWakeup = false;

    /**
     * @brief True when currently processing notification generated by actProactively.
     */
    bool mActingProactively = false;

    /**
     * @brief True if #ask was called at least once during the current notification processing turn.
     * Reset at the start of each notification, set via onAfterToolCall.
     */
    bool mAskCalledThisTurn = false;

    AVector<AArc<Worker>> mWorkers;
    AProperty<size_t> mWorkerCount;
    ASpinlockMutex mWorkingMemoryLock;

    Diary mDiary;
};
